### ISSUE TITLE
Issues building afl-clang-fast with llvm 4.0.0

### ISSUE THREAD

**Issue by pattersonz** [aflgo/aflgo#74]
In my attempted runs of aflgo, I've either gotten tripped up at one of two places, building afl-clang-fast in aflgo/llvm_mode or building the sample project. I've attempted to go through the guide with clang 4.0/4.1/8.0 all with the gold plugin build turned on and pointed at ld.gold. In my experience when running clang 4, I get an error (shown below). If I run with clang4.1 it builds, but then it refuses to build the example project. If I build with 8.0, everything seems to work but there are no results from the CFG extraction and no function targets. (I also tried running the example on a different program with the 8.0 build I wasn't having results there either.)

So my questions are, do you know how I can fix the aflgo/llvm_mode with	clang 4.0, and if not, should this project be able to work with clang 8?

Thanks

```console
Stack dump:
0.      Program arguments: /home/kisamefishfry/llvm4/llvm-project-llvmorg-4.0.0/build/bin/clang-4.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -disable-free -main-file-name test-instr.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -resource-dir /home/kisamefishfry/llvm4/llvm-project-llvmorg-4.0.0/build/bin/../lib/clang/4.0.0 -D _FORTIFY_SOURCE=2 -D AFL_PATH="/usr/local/lib/afl" -D BIN_PATH="/usr/local/bin" -D VERSION="2.52b" -D __AFL_HAVE_MANUAL_CONTROL=1 -D __AFL_COMPILER=1 -D FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1 -D __AFL_LOOP(_A)=({ static volatile char *_B __attribute__((used));  _B = (char*)"##SIG_AFL_PERSISTENT##"; __attribute__((visibility("default"))) int _L(unsigned int) __asm__("__afl_persistent_loop"); _L(_A); }) -D __AFL_INIT()=do { static volatile char *_A __attribute__((used));  _A = (char*)"##SIG_AFL_DEFER_FORKSRV##"; __attribute__((visibility("default"))) void _I(void) __asm__("__afl_manual_init"); _I(); } while (0) -internal-isystem /usr/local/include -internal-isystem /home/kisamefishfry/llvm4/llvm-project-llvmorg-4.0.0/build/bin/../lib/clang/4.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wall -Wno-pointer-sign -fdebug-compilation-dir /home/kisamefishfry/Documents/Research/aflgo/llvm_mode -ferror-limit 19 -fmessage-length 120 -funroll-loops -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -load ../afl-llvm-pass.so -o /tmp/test-instr-37dd8a.o -x c ../test-instr.c
clang-4.0: error: unable to execute command: Segmentation fault (core dumped)
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 4.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
clang-4.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-4.0: error: unable to execute command: Segmentation fault (core dumped)
clang-4.0: note: diagnostic msg: Error generating preprocessed source(s).
Makefile:98: recipe for target 'test_build' failed
make: *** [test_build] Error 254```

**Comment by strongcourage** [comment]
Hi @pattersonz,

Can you provide me some information about your tested program and the targets so that I can try to run AFLGo on my laptop? I did not try AFLGo with clang 8.0, but it seems that AFLGo works stably with clang 4.0.0.

Best.

**Comment by pattersonz** [comment]
@strongcourage ,

Yes, so this error is actually occurring on:
>cd llvm_mode
>make clean all

In step 3 of "How to instrument a Binary with AFLGo" The above text that I shared was the end of the output from the console. We would prefer to get this working with clang-4.0 if possible.

**Comment by strongcourage** [comment]
I see, so you cannot run `make clean all` in /llvm_mode and it failed the run the simple program test-instr.c.
It is probably due to this commit: https://github.com/aflgo/aflgo/commit/0f18be9fef2348aea81ee35d0bdd371dc1db9633

You can revert to the original Makefile, and check again.

**Comment by pattersonz** [comment]
So, I did get a new error, this was the output:

```console
rm -f *.o *.so *~ a.out core core.[1-9][0-9]* test-instr .test-instr0 .test-instr1 
rm -f ../afl-clang-fast ../afl-llvm-pass.so ../afl-llvm-rt.o ../afl-llvm-rt-32.o ../afl-llvm-rt-64.o ../afl-clang-fast++
[*] Checking for working 'llvm-config'...
[*] Checking for working 'clang'...
[*] Checking for '../afl-showmap'...
[+] All set and ready to build.
clang -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.52b\"  afl-clang-fast.c -o ../afl-clang-fast 
ln -sf afl-clang-fast ../afl-clang-fast++
clang++ `llvm-config --cxxflags` -Wl,-znodelete -fno-rtti -fpic -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DVERSION=\"2.52b\" -Wno-variadic-macros -shared afl-llvm-pass.so.cc -o ../afl-llvm-pass.so `llvm-config --ldflags` 
afl-llvm-pass.so.cc:269:9: error: unknown type name 'TerminatorInst'
        TerminatorInst *TI = BB.getTerminator();
        ^
afl-llvm-pass.so.cc:428:11: error: unknown type name 'TerminatorInst'
          TerminatorInst *TI = BB.getTerminator();
          ^
2 errors generated.
Makefile:84: recipe for target '../afl-llvm-pass.so' failed
make: *** [../afl-llvm-pass.so] Error 1

```

**Comment by strongcourage** [comment]
As discussed in https://github.com/aflgo/aflgo/issues/40, you could try LLVM 4.0.1. But it works fine on my machine Ubuntu 16.04 with LLVM 4.0.0. You couild follow the build instruction to install LLVM/clang.
~~~
$ ./afl-clang-fast --version
aflgo-compiler (yeah!) 2.52b
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
~~~

**Comment by pattersonz** [comment]
Sorry, I misread your advice, after reverting the Makefile to the original, I am still getting the same console output.

**Comment by pattersonz** [comment]
So, I was able to get around this issue on a different machine, so it must be some messed up environmental things on my side.
